FROM registry.access.redhat.com/ubi8/nodejs-12:latest

WORKDIR /opt/app-root/src

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy local code to the container image.
COPY index.js ./

# Run the web service on container startup.
CMD [ "npm", "start" ]