apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example-basic-auth-nodejs
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: quay.io/kenmoini/basic-auth-nodejs-service:latest